import ToastProvider from '@/components/toastProvider/ToastProvider';
import './global.css';
import Footer from '@/layouts/footer/Footer';
import Header from '@/layouts/header/Header';
import Providers from '@/redux/Providers';
import NavbarProvider from '@/layouts/navbar/NavbarProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <Header />
          <ToastProvider />
          <NavbarProvider>{children}</NavbarProvider>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
